# Generated by Django 4.1.5 on 2023-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('fnumber', models.TextField(max_length=15)),
                ('age', models.CharField(max_length=3)),
                ('answer', models.CharField(max_length=1)),
            ],
        ),
    ]
