# Generated by Django 4.1.5 on 2023-01-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='lname',
        ),
    ]
