# Generated by Django 4.1.5 on 2023-02-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='INFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField()),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
