# Generated by Django 4.1.5 on 2023-02-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gellery/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
