# Generated by Django 4.1.5 on 2023-02-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_galleryimage_image_alter_serviceimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
