# Generated by Django 4.1.5 on 2023-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_delete_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gellery/')),
            ],
        ),
    ]
